# Generated by Django 4.1.1 on 2022-10-05 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('value', models.PositiveIntegerField(verbose_name='Valor Producto')),
                ('quantity', models.IntegerField(verbose_name='Cantidad Producto')),
                ('producto_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.producto', verbose_name='Producto ID')),
            ],
            options={
                'verbose_name': 'Detalle Pedido',
                'verbose_name_plural': 'Detalle Pedidos',
            },
        ),
    ]
