# Generated by Django 4.1.1 on 2022-09-22 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('number_name', models.CharField(max_length=3, verbose_name='Numero')),
                ('available', models.BooleanField(default=True)),
                ('capacity', models.PositiveIntegerField()),
            ],
        ),
    ]
