# Generated by Django 4.1.1 on 2022-10-05 20:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('number_name', models.CharField(max_length=3, verbose_name='Numero')),
                ('capacity', models.PositiveIntegerField(verbose_name='Capacidad')),
                ('available', models.BooleanField(default=True, verbose_name='Disponibilidad')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario ID')),
            ],
            options={
                'verbose_name': 'Mesa',
                'verbose_name_plural': 'Mesas',
            },
        ),
    ]
