# Generated by Django 4.1.1 on 2022-09-23 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('number_name', models.CharField(max_length=3, verbose_name='Numero')),
                ('available', models.BooleanField(default=True)),
                ('capacity', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Mesa',
                'verbose_name_plural': 'Mesas',
            },
        ),
    ]
