# Generated by Django 4.1.1 on 2022-09-22 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mesas", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mesa",
            name="id",
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
    ]
