# Generated by Django 4.1.1 on 2022-09-23 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Finanzas', 'Finanzas'), ('Cocina', 'Cocina'), ('Bodega', 'Bodega'), ('Cliente', 'Cliente')], default='Cliente', max_length=20),
        ),
    ]
