# Generated by Django 4.1.1 on 2022-10-13 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proveedores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoProveedor',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(verbose_name='Fecha')),
                ('time', models.TimeField(verbose_name='Hora')),
                ('total_value', models.PositiveIntegerField(verbose_name='Valor Total')),
                ('state', models.CharField(max_length=150, verbose_name='Estado de Pago')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proveedores.proveedor')),
            ],
            options={
                'verbose_name': 'Pedido Proveedor',
                'verbose_name_plural': 'Pedidos Proveedor',
            },
        ),
    ]
