# Generated by Django 4.1.1 on 2022-12-06 03:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos_proveedor', '0001_initial'),
        ('facturas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='pedido_proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidos_proveedor.pedidoproveedor', verbose_name=' Pedido Proveedor ID'),
        ),
    ]
