# Generated by Django 4.1.1 on 2022-10-05 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ordenes', '0001_initial'),
        ('platos', '0001_initial'),
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleOrden',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('number_dish', models.PositiveIntegerField(verbose_name='Cantidad de Platos')),
                ('orden_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordenes.orden', verbose_name='Orden ID')),
                ('plato_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='platos.plato', verbose_name='Plato ID')),
                ('producto_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.producto', verbose_name='Producto ID')),
            ],
            options={
                'verbose_name': 'Detalle Orden',
                'verbose_name_plural': 'Detalle Ordenes',
            },
        ),
    ]
