# Generated by Django 4.1.1 on 2022-11-30 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0001_initial'),
        ('detalle_ordenes', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleorden',
            name='orden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordenes.orden', verbose_name='Orden ID'),
        ),
    ]
