# Generated by Django 4.1.1 on 2022-12-06 03:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0001_initial'),
        ('detalle_ordenes', '0003_alter_detalleorden_orden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleorden',
            name='orden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalle_ordenes', to='ordenes.orden', verbose_name='Orden ID'),
        ),
    ]
