# Generated by Django 4.1.1 on 2022-10-13 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plato',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, verbose_name='Nombre Plato')),
                ('description', models.CharField(max_length=150, verbose_name='Descripción')),
                ('recipe', models.TextField(verbose_name='Receta')),
                ('value', models.PositiveIntegerField(verbose_name='Valor Plato')),
                ('type_dish', models.CharField(max_length=150, verbose_name='Tipo de Plato')),
            ],
            options={
                'verbose_name': 'Plato',
                'verbose_name_plural': 'Platos',
            },
        ),
    ]
