# Generated by Django 4.1.1 on 2022-11-03 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plato',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=150)),
                ('recipe', models.TextField()),
                ('value', models.PositiveIntegerField()),
                ('type_dish', models.CharField(max_length=150)),
                ('image_plato', models.URLField(max_length=250)),
                ('score', models.PositiveIntegerField(verbose_name='Puntaje')),
            ],
            options={
                'verbose_name': 'Plato',
                'verbose_name_plural': 'Platos',
            },
        ),
    ]
