# Generated by Django 4.1.1 on 2022-12-06 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plato',
            name='image_plato',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='plato',
            name='score',
            field=models.PositiveIntegerField(),
        ),
    ]
