# Generated by Django 4.1.1 on 2022-10-18 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boleta',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('value', models.PositiveIntegerField(verbose_name='Valor')),
                ('tip', models.PositiveIntegerField(verbose_name='Propina')),
                ('payment_method', models.CharField(max_length=150, verbose_name='Método de Pago')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('time', models.TimeField(verbose_name='Hora')),
                ('state', models.CharField(max_length=150, verbose_name='Estado de Pago')),
            ],
            options={
                'verbose_name': 'Boleta',
                'verbose_name_plural': 'Boletas',
            },
        ),
    ]
