# Generated by Django 4.1.1 on 2022-12-10 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boleta',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('value', models.PositiveIntegerField()),
                ('tip', models.PositiveIntegerField()),
                ('payment_method', models.CharField(max_length=150)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('state', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Boleta',
                'verbose_name_plural': 'Boletas',
            },
        ),
    ]
