# Generated by Django 4.1.1 on 2022-11-04 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boletas', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boleta',
            name='date',
        ),
        migrations.RemoveField(
            model_name='boleta',
            name='time',
        ),
    ]
