# Generated by Django 4.1.1 on 2022-10-14 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0001_initial'),
        ('boletas', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boleta',
            name='orden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boletas', to='ordenes.orden', verbose_name='Orden ID'),
        ),
    ]
