# Generated by Django 4.1.1 on 2022-11-25 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mesas', '0002_initial'),
        ('reservas', '0002_alter_reserva_time_alter_reserva_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='mesa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas_mesa', to='mesas.mesa', verbose_name='Mesa ID'),
        ),
    ]
