# Generated by Django 4.1.1 on 2022-10-13 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('stock', models.PositiveIntegerField(verbose_name='Stock')),
                ('entry_date', models.DateField(verbose_name='Fecha de Ingreso')),
                ('expiration_date', models.DateField(verbose_name='Fecha de Vencimiento')),
                ('value', models.PositiveIntegerField(verbose_name='Precio')),
                ('brand', models.CharField(max_length=150, verbose_name='Marca')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
    ]
