# Generated by Django 4.1.1 on 2022-12-10 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('stock', models.PositiveIntegerField()),
                ('entry_date', models.DateField()),
                ('expiration_date', models.DateField()),
                ('value', models.PositiveIntegerField()),
                ('brand', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
    ]
