# Generated by Django 4.1.1 on 2022-09-23 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('stock', models.PositiveIntegerField(verbose_name='Stock')),
                ('expiration_date', models.DateField(verbose_name='Fecha de Vencimiento')),
                ('measure_unit', models.CharField(max_length=50, unique=True, verbose_name='Unidad de Medida')),
                ('category_product', models.CharField(max_length=50, unique=True, verbose_name='Categoría de Producto')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
    ]
