# Generated by Django 4.1.1 on 2022-10-13 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('daily_total_value', models.IntegerField(verbose_name='Valor Total diario')),
            ],
            options={
                'verbose_name': 'Caja',
                'verbose_name_plural': 'Cajas',
            },
        ),
    ]
