# Generated by Django 4.1.1 on 2022-11-04 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimientos_caja', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientocaja',
            name='date_mov',
            field=models.DateTimeField(verbose_name='Fecha Movimiento'),
        ),
    ]
