# Generated by Django 4.1.1 on 2022-10-26 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0001_initial'),
        ('platos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name_ingredient', models.CharField(max_length=150, verbose_name='Nombre Ingrediente')),
                ('quantity', models.PositiveIntegerField(verbose_name='Cantidad INgrediente')),
                ('plato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredientes', to='platos.plato', verbose_name='Plato ID')),
                ('producto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='productos.producto', verbose_name='Producto ID')),
            ],
            options={
                'verbose_name': 'Ingrediente',
                'verbose_name_plural': 'Ingredientes',
            },
        ),
    ]
